project:
  type: website
  output-dir: docs

website:
  title: "Yihang's Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Projects
      - href: hw1.qmd
        text: Statistics
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
